### ISSUE TITLE
Continuous Integration not working

### ISSUE THREAD

**Issue by m-aciek** [yougov/vr.launch#4]
It looks like since December 2020 travis-ci.org is in read-only mode.

We'd need to migrate to travis-ci.com or set up GitHub Actions. I'd be keen to open a pull request with GitHub Actions config.
For both options an action of @jaraco would be required as only his (yours) credentials will allow for package upload.

**Comment by jaraco** [comment]
This project is based on [jaraco/skeleton](/jaraco/skeleton), meaning it should be possible, even straightforward to merge those changes, including the migration to GH actions.

**Comment by jaraco** [comment]
Note if you merge #6, #7, and #9, [CI in GHA is working](https://github.com/jaraco/vr.launch/actions/runs/1540518136).
